package de.ekert.mavendemo.ki;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/** this is a class generated by ChatGPT 4.0. It contains an off-by-one-error
 * 
 * @author thomase
 *
 */
public class CountdownTimer extends JFrame {
    private int count = 60; // Countdown from 60 seconds
    private JLabel label;
    private Timer timer;

    public CountdownTimer() {
        label = new JLabel(String.valueOf(count), SwingConstants.CENTER);
        timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (count > 0) {
                    count--;
                    label.setText(String.valueOf(count));
                } else {
                    ((Timer) (e.getSource())).stop();
                    JOptionPane.showMessageDialog(null, "Time's up!");
                    // Perform any action after the countdown is over
                }
            }
        });
        initUI();
    }

    private void initUI() {
        setTitle("Countdown Timer");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        label.setFont(label.getFont().deriveFont(48f));
        add(label);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
        timer.start();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new CountdownTimer();
            }
        });
    }
}
